## Cluster
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 2000
# Per the docs, "any value different than zero may result in Redis Cluster
# being unavailable after a master failure... the cluster will return to being
# available only when the original master rejoins the cluster." We... almost
# certainly don't want a single point of failure, so zero it is.
cluster-slave-validity-factor 0
#cluster-migration-barrier %CLUSTER_MIGRATION_BARRIER%
# Default is no
# cluster-allow-reads-when-down no
