# Config file for a single instance of Redis. Adapted from Debian's stock
# /etc/redis/redis.conf, leaving most options at the default.
pidfile /run/redis/redis-server.pid
loglevel notice
logfile /var/log/redis/redis-server.log

dbfilename dump.rdb
dir /var/lib/redis

protected-mode no
